services:

  surrealdb:
    image: surrealdb/surrealdb:latest
    container_name: surrealdb
    user: root
    restart: always
    ports:
      - "80:8000"
    volumes:
      - "./surreal:/surreal_db"
    command:
      - start
      - --log=info 
      - --auth 
      - file:/surreal_db/surreal.db

  mysqldb:
    image: mysql
    restart: always
    volumes:
      - "./mysql:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "81:3306"
