[package]
name = "hdc_shared"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.4.1"
serde = {version = "1.0.188", features = ["derive"]}
serde_json = "1.0.108"
surrealdb = "1.0.2"
toml = "0.8.8"
uuid = {version = "1.6.1", features = ["v4"]}
