name: Create and Publish the Docker images to ghcr.io

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_BACKEND: hdc-server
  IMAGE_NAME_COLLECTOR: hdc-collector

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Restore Cached Target Directory
        id: restore-cache-target
        uses: actions/cache/restore@v4
        with:
          path: /tmp/.buildx-cache
          key: target-artifacts
      
      - name: Build and push Docker images
        id: build-push
        uses: docker/bake-action@v4
        with:
          source: .
          files: ./docker-bake.json
          push: true
          set: |
            *.cache-from=type=local,src=/tmp/.buildx-cache
            *.cache-to=type=local,mode=max,dest=/tmp/.buildx-cache-new
      
      # https://github.com/docker/build-push-action/issues/252
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Cache Target Directory
        id: cache-target
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: target-artifacts
